[tool.black]
line-length = 79
target-version = ["py311"]
exclude = '''
/(
    \.venv
  | \.git
  | __pycache__
)/
'''

[tool.ruff]
line-length = 79
exclude = [".venv", "__pycache__", ".git"]
fix = true

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes (undefined names, etc.)
    "B",   # bugbear (common bugs and security issues)
    "I",   # isort (import sorting)
    "W",   # pycodestyle warnings (e.g., whitespace)
    "UP",  # pyupgrade (Python 3+ syntax suggestions)
]
ignore = [
    "T201",  # allow print()
]

[tool.mypy]
strict = true
ignore_missing_imports = true
exclude = '(\.venv|__pycache__|\.git|tests)'
